apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapid-competitions
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapid-competitions
  template:
    metadata:
      labels:
        app: rapid-competitions
    spec:
      containers:
        - name: rapid-competitions
          image: durjoy22/ostad-kubernetes-assignment:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rapid-competitions-service
  namespace: production
spec:
  type: NodePort
  selector:
    app: rapid-competitions
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
